### ISSUE TITLE
Library does not compile for the Arduino ARM or AVR boards

### ISSUE THREAD

**Issue by tigoe** [m2ag-labs/m2aglabs_ohmite#1]
Steps to duplicate:

1. open allthreetypes example
2. choose "Arduino Due" for board type
3. compile.  

This gives the following error: 

````
/Users/username/Documents/Arduino/libraries/m2aglabs_ohmite-master/M2aglabs_Ohmite.cpp: In member function 'int16_t M2aglabs_Ohmite::_getLinearPosition(boolean)':
/Users/username/Documents/Arduino/libraries/m2aglabs_ohmite-master/M2aglabs_Ohmite.cpp:227:18: error: 'INPUT_PULLDOWN' was not declared in this scope
  pinMode(_V_REF, INPUT_PULLDOWN);
                  ^
exit status 1
Error compiling for board Arduino Due (Native USB Port).
````

Seems to work fine on the SAMD based boards, but not the ARM or AVR boards though. Compiling for an Uno or Leonardo results in the following error:

````










/Users/thomasigoe/Documents/Arduino/libraries/m2aglabs_ohmite-master/examples/allthreetypes/allthreetypes.ino: In function 'void setup()':
allthreetypes:36:2: error: 'analogReadResolution' was not declared in this scope
  analogReadResolution(ANALOG_RESOLUTION);
  ^~~~~~~~~~~~~~~~~~~~
/Users/thomasigoe/Documents/Arduino/libraries/m2aglabs_ohmite-master/examples/allthreetypes/allthreetypes.ino:36:2: note: suggested alternative: 'analogRead'
  analogReadResolution(ANALOG_RESOLUTION);
  ^~~~~~~~~~~~~~~~~~~~
  analogRead
exit status 1
'analogReadResolution' was not declared in this scope
````

This error was reported to me by David Cool.

**Comment by MarcGraham** [comment]
Hi, 
Yep, only tested on samd devices. Do you have a proposed fix? I'd be glad to take a pull request.

It will be a week or so before I get to this.

**Comment by tigoe** [comment]
I don't have a proposed fix, sorry; again, I'm reporting a bug that was passed to me second hand, so I haven't dig too deep. But it looks like there are some architecture specific calls like [this one on line 227](https://github.com/m2ag-labs/m2aglabs_ohmite/blob/master/M2aglabs_Ohmite.cpp#L227) that might need to be generalized. A simple workaround would be to modify your [library.properties file](https://arduino.github.io/arduino-cli/latest/library-specification) to state that it only works on SAMD. It'll report an error for folks who try to use it on an unsupported platform.  

A more constructive fix would be to clear out the platform-specific calls like the one on line 227. Can you work without the internal pulldowns and the VRef and just use VCC direct? Sorry I can't get more specific than that without more analysis, but that's  might be a start. 

Also, I should have said to begin with: really handy library,  thank you. It's made me really enjoy these sensors.

**Comment by MarcGraham** [comment]
I am glad you find the driver useful. 

I think I have the issues resolved. 
I set input pull_up to just input. Works the same in my testing. 

I commented out the SAMD specific analog resolution stuff. The sensors work fine with 10 bit resolution. Higher resolutions can be set if desired. 
 
It compiles for AVR and ARM but I have no devices to test with. 

Version bumped 1.0.1.

**Comment by tigoe** [comment]
Thank you! I can confirm that it works on an Uno, tho my test was pretty basic (compiled your examples and mine and ran on an Uno I had already wired up)
